### ISSUE TITLE
In a code block, using multiple OR operators (||) in the same line will get filtered 

### ISSUE THREAD

**Issue by asdfugil** [DiscordGIR/GIRRewrite#16]
a message like this will get filtered even though it does not have any spoliers at all

<img width="754" alt="螢幕截圖 2022-11-25 下午9 27 29" src="https://user-images.githubusercontent.com/42699250/203995537-cce587ea-bf05-4fad-a86e-bf5a572d25d5.png">

**Comment by SlimShadyIAm** [comment]
Thanks but this is a known issue, AFAIK it's not possible to fix it without opening up the possibility for bypassing the filter, unless you are able to find a solution.
